### ISSUE TITLE
Consider replacing kitsu.js with kitsu

### ISSUE THREAD

**Issue by wopian** [Dev-Yukine/Senpai#18]
[kitsu.js](https://yarnpkg.com/en/package/kitsu.js) is deprecated in favour of the more feature complete [kitsu](https://yarnpkg.com/en/package/kitsu) package that is fully JSON-API compliant.

Based on [your current usage], search implementation would be something like:

```js
const Kitsu = require('kitsu')
const kitsu = new Kitsu()

const { data } = await kitsu.fetch('anime', {
 filters: {
   text: params.join(' ')
 }
}
...
await msg.channel.send(`**Title JP:** ${data[number].titles.ja_jp`)
...
```

[your current usage]:
https://github.com/Dev-Yukine/Senpai/blob/99215e0243fcfbc7d2108b1e4b39948789ee48c9/src/commands/fun/anime.js#L29

**Comment by Dev-Yukine** [comment]
oh i see didn't noticed that Crawl deprecated the kitsu.js pacakge will rewrite my code with your package now should not take that long
